### ISSUE TITLE
Error: No such object: platform-dns

### ISSUE THREAD

**Issue by jani123** [7ojo/perl6-platform#1]
```
$ perl6 -Ilib bin/platform create        
» Service
Error: No such object: platform-dns
Type check failed in assignment to $dns-addr; expected Str but got Any (Any)
  in method start at /home/jani/workspace/platform/lib/Platform/Docker/DNS.pm6 (Platform::Docker::DNS) line 26
  in block  at /home/jani/workspace/platform/lib/Platform.pm6 (Platform) line 15
  in sub MAIN at bin/platform line 25
  in block <unit> at bin/platform line 89
```

This is because platform cannot start new docker-dns-gen container when host has own dns server(dnsmasq in this case) installed in same 53 port.

Hotfix would be to remove `--publish 53:53/udp` from lib/Platform/Docker/DNS.pm6 and configure own dnsmasq accordingly.

Proper fix would be:
* First of all, platform should tell that port is in use
* And platform shouldn't publish dsn port if it's already in use and tell the user a warning that one needs to configure his dns server somehow or atleast option to prevent port publishing

**Comment by 7ojo** [comment]
Fixed in b8c5e2bf
