### ISSUE TITLE
"Use of uninitialized value" on remove

### ISSUE THREAD

**Issue by jani123** [7ojo/perl6-platform#21]
$_platform remove environment.yml 
Use of uninitialized value % of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /somehwere/xxx (App::Platform) line 40
  │ Summary
  │ project1
  │ project2
  │ ...

**Comment by 7ojo** [comment]
Fixed in 1065877b
