### ISSUE TITLE
Unitialized value in string context error when using platform commands

### ISSUE THREAD

**Issue by samuliy** [7ojo/perl6-platform#25]
An error message appears when running `platform run` or `platform stop`. Does not block usage of platform.
```
Use of uninitialized value % of type Any in string context.
Methods .^name, .perl, .gist, or .say can be used to stringify it to something meaningful.
  in block  at /home/samuliy/.local/share/perl6/site/sources/EDA28A884E8D09BF60DF8ABB7C1D83B8CC5882AB (App::Platform) line 40
```

Debian Stretch

Rakudo Star version 2017.10 built on MoarVM version 2017.10

Docker version 17.12.0-ce, build c97c6d6

**Comment by 7ojo** [comment]
Thanks! That's fixed on HEAD now
