### ISSUE TITLE
Projects with '-' in directory name seem to not stop correctly

### ISSUE THREAD

**Issue by samuliy** [7ojo/perl6-platform#27]
Sometimes when stopping a project and running it again the user gets an error message:
```
  │ example/foo-bar
  └─ docker: Error response from daemon: Conflict. The container name "/foo-bar" is already in use by container "b4e625d8288b9d73ee32312201e4dfbdc83610d18e33497d96ab9baa1a9830ea". You have to remove (or rename)
    that container to be able to reuse that name. See 'docker run --help'.
```
Seems to happen with directories that have a '-' character

**Comment by 7ojo** [comment]
If I understand correctly you mean running like this:
```
$ platform run example/foo-bar
$ platform stop example/foo-bar
$ platform run example/foo-bar
--> ERROR MESSAGE
```
Correct? 

If so then you have understanded incorrectly use of those run/stop/start/remove. Stop is more like "suspend" same as docker stop <container>. Most common usage is just 

1. `platform run <projectdir>`
2. (do your thing)
3. `platform remove <projectdir>`

**Comment by samuliy** [comment]
Okay, probably a misunderstanding with the commands. I'll close this ticket and reopen if I get the error message again elsewhere, since I have not seen it in a while now
